spring:
  application:
    name: springcloud-user
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.200:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId:  ${spring.cloud.client.ipAddress}:${server.port}
